apiVersion: v1
kind: Pod
metadata:
  name: sample6
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - sleep
        - "100000"
      env:
        - name: URL
          value: google.com