apiVersion: v1
kind: Pod
metadata:
  name: security
spec:
  containers:
    - name: security
      image: pavanvere/pavanzs.online-security
      securityContext:
        #runAsUser: 2000
        runAsNonRoot: true

---
apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  containers:
    - name: docker
      image: docker
      securityContext:
        privileged: true
      command:
        - sleep
        - "1000000"