apiVersion: v1
kind: Pod
metadata:
  name: fruit
  labels:
    fruit_name: Berry
    imported_from: kerala
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - sleep
        - "10000000"